@startuml "figure7_adapter_class"

caption figure7: Class Adapter

interface Target{
    + targetInterface(): void
}

interface Adaptee{
    + originalInterface(): void
}

class Adapter{

}

Adapter --|> Target
Adapter --|> Adaptee

@enduml