@startuml "figure10_decorator"
caption figure10: Decorator

abstract class AbstractComponent{
    + behavior(): void
}
class ConcreteComponent{}
abstract class AbstractDecorator{}
class ConcreteDecorator{
    + newBehavior(): void
}

AbstractComponent <|-- ConcreteComponent
AbstractComponent <|-- AbstractDecorator
AbstractDecorator o-- AbstractComponent
AbstractDecorator <|-- ConcreteDecorator
@enduml