@startuml "figure14_chain"
caption figure14: Chain

abstract class Handler{
    - successor: Handler*
    + handleRequest()
}

class ConcreteHandlerA{}
class ConcreteHandlerB{}

Handler <|-- ConcreteHandlerA
Handler <|-- ConcreteHandlerB

Handler o-- Handler

@enduml