@startuml "figure15_command"
caption figure 15: Command

interface Command{
    + execute(): void
}

class ConcreteCommand{}

class Invoker{
    - commandList: List<Command>
    + invoke(): void
}

class Receiver{
    + action(): void
}

class Client{}

Command <|-- ConcreteCommand
Invoker o-right- Command
Receiver  <-right- ConcreteCommand
Client .up.> Invoker
Client ..> ConcreteCommand
@enduml