@startuml "figure20_observer"
caption figure 20: Observer

interface Subject{
    + addObserver(observer:Observer) : void
    + removeObserver(observer:Observer) : void
    + notifyObservers() : void
}

interface Observer{
    + update() : void
}

class ConcreteSubject{
}

class ConcreteObserver{

}

Subject <|-- ConcreteSubject
Observer <|-- ConcreteObserver

Subject -right-> Observer : use
@enduml


@startuml "figure20_observer_case"
caption figure 20: Observer case

interface Product{
    + addBuyer(user:Buyer*) : void
    + removeBuyer(user:Buyer*) : void
    + notifyBuyers() : void
    + setAmount(amount:int) : void
}

interface Buyer{
    + action() : void
}

class IPhoneX{
    - buyers : std::List<Buyer*>
    - amount : int
}

class BuyerA{}

class BuyerB{}



Product <|-- IPhoneX
Buyer <|-- BuyerA
Buyer <|-- BuyerB

Product -right-> Buyer : use
@enduml